services:
  agent:
    # Image must be set to latest or to a specific tag that watchtower can watch
    # The tag must be updated when a new version is available
    image: portainer/agent:latest
    container_name: portainer_agent
    environment:
      - EDGE=1
      - EDGE_INSECURE_POLL=1
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}
      - LOG_LEVEL=debug
      # - CAP_HOST_MANAGEMENT=1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    networks:
      - portainer_agent_net
  watchtower:
    image: containrrr/watchtower:latest
    container_name: auto_updater
    # Only manage Portainer agent auto-upgrade and cleanup old Docker image afterwards (default polling interval is 24h) 
    command: portainer_agent --cleanup 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  portainer_agent_net:

volumes:
  portainer_agent_data:
