version: '3.3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    configs:
      - source: index
        target: /usr/share/nginx/html/index.html
configs:
  index:
    file: ./www/index.html