services:
  portainer:
    image: portainerci/portainer:pr6864
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
  ov-watcher:
    image: deviantony/fdo-ov-watcher
    restart: unless-stopped
    configs:
      - source: ov-watcher-config
        target: /config.yml
    volumes:
      - type: bind
        source: ./ov_output
        target: /ov_output
  web-server:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8077:80
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: bind
        source: ./ov_output
        target: /ov_output

configs:
  ov-watcher-config:
    file: ./config/config.yml
  nginx-config:
    file: ./config/default.conf

volumes:
  portainer_data: