services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  portainer1:
    image: portainer/portainer-ee:latest

  portainer2:
    image: portainer/portainer-ee:latest
