version: '3'
services:
  agent:
    image: portainer/agent:2.12.2
    deploy:
      mode: global    
    environment:
      - EDGE=1
      - EDGE_INSECURE_POLL=1
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}
      - AGENT_CLUSTER_ADDR=tasks.agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    networks:
      - portainer_agent_net

networks:
  portainer_agent_network:
    driver: overlay

volumes:
  portainer_agent_data:
