services:

  registry:
    image: registry:2
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
    secrets:
      - source: htpasswd
        target: /auth/htpasswd
      - source: tls-cert
        target: /certs/registry.crt
      - source: tls-key
        target: /certs/registry.key
    networks:
      - networkB

  swarm-manager1:
    image: deviantony/dind:20.10.16
    privileged: true
    stdin_open: true
    tty: true
    configs:
      - source: setup_registry_mirror
        target: /tmp/setup-registry-mirror.sh
    secrets:
      - source: htpasswd-mirror
        target: /auth/htpasswd
      - source: tls-cert
        target: /certs/registry.crt
      - source: tls-key
        target: /certs/registry.key
      - source: tls-cert
        target: /etc/docker/certs.d/registry.dev:5000/ca.crt
    networks:
      - networkA
      - networkB
    links:
      - registry:registry.dev
  
  swarm-worker1:
    image: deviantony/dind:20.10.16
    privileged: true
    stdin_open: true
    tty: true
    configs:
      - source: docker_daemon_worker
        target: /etc/docker/daemon.json  
    secrets:
      - source: tls-cert
        target: /etc/docker/certs.d/registry-mirror.dev:5000/ca.crt
    networks:
      - networkA
    links:
      - swarm-manager1:registry-mirror.dev
  
  swarm-worker2:
    image: deviantony/dind:20.10.16
    privileged: true
    stdin_open: true
    tty: true
    configs:
      - source: docker_daemon_worker
        target: /etc/docker/daemon.json
    secrets:
      - source: tls-cert
        target: /etc/docker/certs.d/registry-mirror.dev:5000/ca.crt   
    networks:
      - networkA
    links:
      - swarm-manager1:registry-mirror.dev
  
  swarm-conductor:
    image: deviantony/sind-conductor:latest
    environment:
      WAIT_HOSTS: swarm-manager1:2376, swarm-worker1:2376, swarm-worker2:2376
      WAIT_TIMEOUT: 60
      SWARM_MANAGERS: swarm-manager1
      SWARM_WORKERS: swarm-worker1,swarm-worker2
      NIC: eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - networkA

networks:
  networkA:
    internal: true
  networkB:

configs:
  docker_daemon_manager:
    file: ./conf/daemon-manager.json
  docker_daemon_worker:
    file: ./conf/daemon-worker.json
  setup_registry_mirror:
    file: ./setup-registry-mirror.sh

secrets:
  tls-cert:
    file: ./certs/registry.crt
  tls-key:
    file: ./certs/registry.key
  htpasswd:
    file: ./auth/htpasswd
  htpasswd-mirror:
    file: ./auth/htpasswd-mirror