services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
  
  portainer-ce:
    image: portainer/portainer-ce:2.11.1-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - portainer_data_ce:/data
    labels:
      caddy: "https://container-sandbox.local"
      caddy.handle_path: /portainer-be*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 9443}}"
      caddy.handle_path.1_reverse_proxy: "{{upstreams 8000}}"

  portainer-be:
    image: portainer/portainer-ee:2.12.1-alpine
    restart: unless-stopped
    networks:
      - caddy    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - portainer_data_be:/data    
    labels:
      caddy: "https://container-sandbox.local"
      caddy.handle_path: /portainer-ce*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 9443}}"
      caddy.handle_path.1_reverse_proxy: "{{upstreams 8000}}"

  registry:
    image: registry:2
    restart: unless-stopped
    networks:
      - caddy    
    volumes:
      - registry_data:/var/lib/registry
    labels:
      caddy: "http://container-sandbox.local"
      caddy.handle_path: /registry*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 5000}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data:
  portainer_data_ce:
  portainer_data_be:
  registry_data: