services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
  
  portainer-ce:
    image: portainer/portainer-ce:2.11.1-alpine
    restart: unless-stopped
    # For Edge deployments, as TCP reverse proxy is not supported by Caddy
    # Port range 10000-19999 for CE
    ports:
      - 19443:9443
      - 18000:18000
    command: --tunnel-port 18000
    networks:
      - caddy    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - portainer_data_ce:/data
    labels:
      caddy: "http://container-sandbox.local"
      caddy.handle_path: /portainer-ce*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 9000}}"

  portainer-be:
    image: portainer/portainer-ee:2.12.2-alpine
    restart: unless-stopped
    # For Edge deployments, as TCP reverse proxy is not supported by Caddy
    # Port range 20000-29999 for BE
    ports:
      - 29443:9443
      - 28000:28000
    command: --tunnel-port 28000      
    networks:
      - caddy    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - portainer_data_be:/data    
    labels:
      caddy: "http://container-sandbox.local"
      caddy.handle_path: /portainer-be*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 9000}}"

  registry:
    image: registry:2
    restart: unless-stopped
    networks:
      - caddy    
    volumes:
      - registry_data:/var/lib/registry
    labels:
      caddy: "http://container-sandbox.local"
      caddy.handle_path: /registry*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 5000}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data:
  portainer_data_ce:
  portainer_data_be:
  registry_data: