services:
  ov-watcher:
    image: deviantony/fdo-ov-watcher
    restart: unless-stopped
    configs:
      - source: ov-watcher-config
        target: /config.yml
    volumes:
      - type: bind
        source: ./ov_output
        target: /ov_output
  web-server:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8077:80
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: bind
        source: ./ov_output
        target: /ov_output

configs:
  ov-watcher-config:
    file: ./config/config.yml
  nginx-config:
    file: ./config/default.conf
