version: '3.3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    configs:
      - source: index
        target: /usr/share/nginx/html/index.html
        # mode: 0644
        # owner: root:root
        # group: root:root
configs:
  index:
    file: ./www/index.html